before_install:
  sudo: required

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose build
  - docker-compose start
  - sleep 90
  - curl --retry 3 --retry-delay 5 -v http://localhost:8080/fedora
  - curl --retry 3 --retry-delay 5 -v http://localhost:8080/solr
  - curl --retry 3 --retry-delay 5 -v http://localhost:8080/fedoragsearch
