mysql:
  image: mysql:latest
  command: mysqld --skip-name-resolve
  environment:
    MYSQL_ROOT_PASSWORD: fedora
    MYSQL_USER: fedora
    MYSQL_PASSWORD: fedora
    MYSQL_DATABASE: fedora3
  expose:
   - "3306"
fedorasolrgsearch:
  image: unblibraries/fedora-solr-gsearch:3.8.x
  links:
    - mysql:mysql
  expose:
   - "8080"
  ports:
    - "8080:8080"
  environment:
    DRUPAL_DB_NAME: islandorap_db
    DRUPAL_DB_USER: islandorap_user
    DRUPAL_DB_PASSWORD: fedora
drupal:
  build: drupal
  links:
    - mysql:mysql
    - fedorasolrgsearch:fedorasolrgsearch
  expose:
   - "80"
  ports:
    - "80:80"
  environment:
    MYSQL_ROOT_PASSWORD: fedora
    DRUPAL_DB_PASSWORD: fedora
    ISLANDORA_VERSION: 7.x-1.5
